name: 小福助手 
version: 1.0

logging:
  level: debug

# 唤醒词
WakeWord: 小福

interrupt: true
# 是否开启工具调用
StartTaskMode: true
# 具体处理时选择的模块
selected_module:
  Recorder: WebSocketRecorder
  ASR: FunASR
  VAD: SileroVAD
  LLM: DifyLLM
  TTS: KOKOROTTS
  Player: WebSocketPlayer

Recorder:
  RecorderPyAudio:
    output_file: tmp/
  WebSocketRecorder:
    output_file: tmp/


ASR:
  FunASR:
    model_dir: FunAudioLLM/SenseVoiceSmall  # 这是专门针对中文优化的模型
    output_file: tmp/
    # 可以尝试其他中文模型：
    # model_dir: "damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
    # model_dir: "damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch"

VAD:
  SileroVAD:
    sampling_rate: 16000
    threshold: 0.6        # 从0.5增加到0.6，减少误触发
    min_silence_duration_ms: 1500  # 增加到1.5秒，确保一句话说完

LLM:
  OpenAILLM:
    model_name: deepseek-chat
    url: https://api.deepseek.com
    api_key: sk-aa6c59dfe95a489a939be5a878cae0c9
  OllamaLLM:
    model_name: qwen-chat
    url: http://localhost:11434/api/chat # 注意后缀是api/chat
    api_key:
  DifyLLM:
    url: http://115.190.170.250:8088/v1  # Dify API地址，如果是自部署请修改
    api_key: app-i4OwEjCdRMkSqgA7o1DGpMzr  # 在Dify应用中获取API Key
    user: bailing-user  # 用户标识，可自定义


TTS:
  MacTTS:
    voice: Tingting
    output_file: tmp/
  EdgeTTS:
    voice: zh-CN-XiaoxiaoNeural
    output_file: tmp/
  GTTS:
    lang: zh
    output_file: tmp/
  CosyvoiceTTS:
    output_file: tmp/
  CHATTTS:
    output_file: tmp/
  KOKOROTTS:
    output_file: tmp/
    lang: z
    voice: zf_001
    repo_id: hexgrad/Kokoro-82M-v1.1-zh

Player:
  PygameSoundPlayer: null
  PygamePlayer: null
  CmdPlayer: null
  PyaudioPlayer: null
  WebSocketPlayer: null

Rag:
  doc_path: documents/
  emb_model: models/bge-small-zh
  model_name: deepseek-chat
  url: https://api.deepseek.com
  api_key: sk-aa6c59dfe95a489a939be5a878cae0c9

Memory:
  dialogue_history_path: tmp/
  memory_file: tmp/memory.json
  model_name: deepseek-chat
  url: https://api.deepseek.com
  api_key: sk-aa6c59dfe95a489a939be5a878cae0c9

TaskManager:
  functions_call_name: plugins/function_calls_config.json
  aigc_manus_enabled: false





