name: 小福助手 
version: 1.0

logging:
  level: debug

# 唤醒词
WakeWord: 小福

interrupt: true
# 是否开启工具调用
StartTaskMode: true
# 具体处理时选择的模块
selected_module:
  Recorder: WebSocketRecorder
  ASR: FunASR
  VAD: SileroVAD
  LLM: DifyLLM  # 使用Dify作为LLM
  TTS: KOKOROTTS
  Player: WebSocketPlayer

Recorder:
  RecorderPyAudio:
    output_file: tmp/
  WebSocketRecorder:
    output_file: tmp/


ASR:
  FunASR:
    model_dir: FunAudioLLM/SenseVoiceSmall  # 这是专门针对中文优化的模型
    output_file: tmp/

VAD:
  SileroVAD:
    sampling_rate: 16000
    threshold: 0.6        # 从0.5增加到0.6，减少误触发
    min_silence_duration_ms: 1500  # 增加到1.5秒，确保一句话说完

LLM:
  OpenAILLM:
    model_name: deepseek-chat
    url: https://api.deepseek.com
    api_key: sk-your-deepseek-key
  OllamaLLM:
    model_name: qwen-chat
    url: http://localhost:11434/api/chat # 注意后缀是api/chat
    api_key:
  DifyLLM:
    # Dify云服务地址（官方）
    url: https://api.dify.ai/v1
    # 如果使用自部署版本，修改为你的服务地址，例如:
    # url: http://localhost/v1
    # url: http://your-domain.com/v1
    
    # 在Dify应用中获取的API密钥
    # 格式: app-xxxxxxxxxxxxx
    api_key: app-YOUR_API_KEY_HERE
    
    # 用户标识，用于区分不同用户的对话
    # 相同user会共享对话历史
    user: bailing-user


TTS:
  MacTTS:
    voice: Tingting
    output_file: tmp/
  EdgeTTS:
    voice: zh-CN-XiaoxiaoNeural
    output_file: tmp/
  GTTS:
    lang: zh
    output_file: tmp/
  CosyvoiceTTS:
    output_file: tmp/
  CHATTTS:
    output_file: tmp/
  KOKOROTTS:
    output_file: tmp/
    lang: z
    voice: zf_001
    repo_id: hexgrad/Kokoro-82M-v1.1-zh

Player:
  PygameSoundPlayer: null
  PygamePlayer: null
  CmdPlayer: null
  PyaudioPlayer: null
  WebSocketPlayer: null

Rag:
  doc_path: documents/
  emb_model: models/bge-small-zh
  model_name: deepseek-chat
  url: https://api.deepseek.com
  api_key: sk-your-deepseek-key

Memory:
  dialogue_history_path: tmp/
  memory_file: tmp/memory.json
  model_name: deepseek-chat
  url: https://api.deepseek.com
  api_key: sk-your-deepseek-key

TaskManager:
  functions_call_name: plugins/function_calls_config.json
  aigc_manus_enabled: false

